[package]
name = "dir-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { vesion="1.0.152", features=["derive"] }
serde_json = "1.0.91"
walkdir = "2.3.2"
